config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Show all tasks
  get "/tasks", to: "tasks#index"



  #Create a new task
  get "/tasks/new", to: "tasks#new"
  post "/tasks", to: "tasks#create"


  #Update
  get "/tasks/:id/edit", to: "tasks#edit", as: :task_edit

  #Show one task
  get "/tasks/:id", to: "tasks#show", as: :task
  patch "/tasks/:id", to: "tasks#update"

  #Destroy
  delete "/tasks/:id", to: "tasks#destroy", as: :task_destroy


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def create
  end

  def update
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    redirect_to tasks_path

  end

  def new
  end

  def create
    Task.create(name: params[:name], details: params[:details], status: false)
    redirect_to tasks_path
  end

  def show
    id = params[:id]
    @task = Task.find(id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    # status = params[:status] ? "Done" : "To be done"
    task.update(name: params[:name], details: params[:details], status: params[:status])


    redirect_to tasks_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<form action=<%= task_path(@task) %> method="post">
  <input type="hidden" name="_method" value="patch">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" value="<%= @task.name %>">
  <input type="text" name="details" value="<%= @task.details %>">
  <input type="checkbox" name="status">
  <input type="submit" value="Submit">
</form>

app/views/tasks/index.html.erb
<ul>
  <% @tasks.each do |task| %>
    <li>
      [<%= task.status ? "X" : " " %>] <a href="tasks_path(task) %>"> <%= task.name %> </a>
      <%= link_to "Delete", task_destroy_path(task), method: "delete" %>
      <a href="<%= task_edit_path(task) %>">Update</a>

      <form action=<%= task_path(task) %> method="post">
        <input type="hidden" name="_method" value="patch">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

        <input type="text" name="name" class="hidden" value="<%= task.name %>">
        <input type="text" name="details" class="hidden" value="<%= task.details %>">
        <input type="checkbox" name="status" checked="true" class="hidden">
        <input type="submit" value="Mark as Done">
    </form>

    </li>
  <% end %>
</ul>

<a href="<%= tasks_new_path %>">Create a new task</a>

app/views/tasks/new.html.erb
<form action=<%= tasks_path  %> method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Task name...">
  <input type="text" name="details" placeholder="Task details...">
  <input type="submit" value="Submit">
</form>

app/views/tasks/show.html.erb
<%= @task.name %> - <%=  @task.details %> - <%= @task.status ? "Done" : "To be done" %>

<a href="<%= task_edit_path(@task) %>">Update</a>

<%= link_to "Delete", task_destroy_path, method: "delete" %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>